### ISSUE TITLE
Licensgate - Validation

### ISSUE THREAD

**Issue by avlrr** [DevLeoko/license-gate#1]
![image](https://github.com/DevLeoko/license-gate/assets/165609589/d0ca9ca3-5454-4c8f-b17a-7836aaf9273d)
![image](https://github.com/DevLeoko/license-gate/assets/165609589/b224ebd3-d818-4e0a-b577-1bc63b28e9c7)
Cannot resolve method 'isValid' in 'ValidationType'

**Comment by Hopefuls** [comment]
Ensure you're on the latest version of the licensegate-java wrapper. Check the docs regarding the maven or gradle setup for that: https://docs.licensegate.io/wrappers/java

I am unable to reproduce the issue you're facing on the latest version, which is 1.0.3

The issues section of this repository should not be used as a way to receive support. Support is mainly provided over our discord @ https://discord.gg/zycVCTn67K

**Comment by avlrr** [comment]
Ah yes, It was indeed the version.. I was on 1.0.0 because that's what it says on spigotmc, might wanna change that.
![image](https://github.com/DevLeoko/license-gate/assets/165609589/72b4d6c8-52c5-4fea-af01-d68a7395afff)
