### ISSUE TITLE
license key for number of devices

### ISSUE THREAD

**Issue by CurlyBytes** [DevLeoko/license-gate#4]
Hi @DevLeoko 

Can you provide an example how to use this one in my current use case

i have 2 license type, Consumers and Enterprise, the organization can just either of this 2,
currently development mobile app, how to implement license limitation where in the Consumers license is limited only to 10 mobile devices

while the Enterprise, is limited only to 25 devices, how do i achieve this one,  should i create 35 licenses each(25 enterprise and 10 consumers)? or is there a better way to manage it, please advise

Also i submit a pull request to help https://github.com/DevLeoko/license-gate/pull/3, this pr is making the tool to working on docker and docker compose(currently this is for local development),feel free to try it thanks!

**Comment by DevLeoko** [comment]
We currently don't actively support any use cases where you would detect devices (based on any device identifiers).

You could pass a device identifier (e.g. IMEI number) as the scope of the license and then have one license per device. But for this you first have to know the IMEI and then create a license.

The easiest way would probably be to set a rate limit of 10 verifications per hour and have a background task in your app that verifies the license once per hour. This way the user could also switch devices but could never use more than 10 devices at a time.

Let us know if you have suggestions on how to support such use cases better.

**Comment by CurlyBytes** [comment]
may i know what are the other uses cases to other consumers/community on how they implement it? if you those information i would love to have that white papers to read and study on how did they implement it thanks

**Comment by DevLeoko** [comment]
We are not aware of any white papers on this topic.
There are some use cases outlined in our docs: https://docs.licensegate.io/ (on the about page)

**Comment by CurlyBytes** [comment]
Aside from the use case outline in the docs are there are other  information that we can refer? please advise thanks!

**Comment by DevLeoko** [comment]
Not really sorry. Those are the use cases that we have in mind when developing this system. If you have any more specific questions or comments, I'd be happy to help

**Comment by CurlyBytes** [comment]
Okay got it, you may close this ticket thanks!
