### ISSUE TITLE
Can API key functionality be supported for self hosted versions?

### ISSUE THREAD

**Issue by Shizoukia** [DevLeoko/license-gate#5]
.

**Comment by Hopefuls** [comment]
It should be supported, are you experiencing any issues regarding it?

**Comment by Shizoukia** [comment]
> It should be supported, are you experiencing any issues regarding it?

No, I'm just asking this question because it seems like they haven't updated this repository for a long time

**Comment by Shizoukia** [comment]
The self hosted compiled version seems to lack API related support

**Comment by DevLeoko** [comment]
The hosted version is exactly the same as the self-hosted. There are currently a few known issues with the API, but overall it should work just as on the hosted version

**Comment by Shizoukia** [comment]
> The hosted version is exactly the same as the self-hosted. There are currently a few known issues with the API, but overall it should work just as on the hosted version

huh.. imean API Key
I cloned the repository a month ago and compiled it. It doesn't have apikey functionality

![image](https://github.com/user-attachments/assets/f4bb9cc7-011e-4a97-b6be-84faf5dcf857)
![image](https://github.com/user-attachments/assets/8db4e634-0a91-4cb1-92b8-dbc87ba79039)

**Comment by DevLeoko** [comment]
This menu item and management page were added 5 Months ago: https://github.com/DevLeoko/license-gate/commit/71d14c0909955d79f7136310c559e0790eac4610

**Comment by Shizoukia** [comment]
> This menu item and management page were added 5 Months ago: [71d14c0](https://github.com/DevLeoko/license-gate/commit/71d14c0909955d79f7136310c559e0790eac4610)

What? okay let me check it

Is this enabled by default or do some settings need to be changed
I am trying to rebuild a new one

**Comment by Shizoukia** [comment]
![image](https://github.com/user-attachments/assets/76f3ed8d-21e2-42a0-8894-e7c28158c596)
Okay, I'm sorry for my mistake. I was very stupid and may have used an old version of the source code (I cloned once a few months ago, and a month ago when I tried to build, I may have used the old version of the source code)
